SET IDENTITY_INSERT [dbo].[Music] ON
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (1, N'Shape of You', N'CD', N'Ed Sheeran', N'Pop', 2017, CAST(15.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (2, N'Photograph', N'Digital', N'Ed Sheeran', N'Pop', 2014, CAST(12.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (3, N'Castle on the Hill', N'Vinyl', N'Ed Sheeran', N'Pop', 2017, CAST(18.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (4, N'Uptown Funk', N'Vinyl', N'Mark Ronson ft. Bruno Mars', N'Funk', 2014, CAST(18.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (5, N'Valerie', N'Digital', N'Mark Ronson ft. Amy Winehouse', N'Soul', 2007, CAST(14.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (6, N'Nothing Breaks Like a Heart', N'CD', N'Mark Ronson ft. Miley Cyrus', N'Pop', 2018, CAST(16.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (7, N'Blinding Lights', N'CD', N'The Weeknd', N'R&B', 2020, CAST(17.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (8, N'Starboy', N'Vinyl', N'The Weeknd ft. Daft Punk', N'Pop', 2016, CAST(19.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (9, N'Save Your Tears', N'Digital', N'The Weeknd', N'Pop', 2020, CAST(16.49 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (10, N'Dance Monkey', N'CD', N'Tones and I', N'Pop', 2019, CAST(16.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (11, N'Never Seen the Rain', N'Digital', N'Tones and I', N'Pop', 2019, CAST(13.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (12, N'Fly Away', N'Vinyl', N'Tones and I', N'Pop', 2020, CAST(18.49 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (13, N'Someone You Loved', N'Vinyl', N'Lewis Capaldi', N'Pop', 2018, CAST(21.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (14, N'Before You Go', N'CD', N'Lewis Capaldi', N'Pop', 2019, CAST(20.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (15, N'Hold Me While You Wait', N'Digital', N'Lewis Capaldi', N'Pop', 2019, CAST(22.49 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (16, N'Bad Romance', N'Digital', N'Lady Gaga', N'Pop', 2009, CAST(14.49 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (17, N'Shallow', N'Vinyl', N'Lady Gaga, Bradley Cooper', N'Pop', 2018, CAST(17.49 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (18, N'Rain on Me', N'CD', N'Lady Gaga, Ariana Grande', N'Pop', 2020, CAST(16.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (19, N'Before He Cheats', N'CD', N'Carrie Underwood', N'Country', 2005, CAST(14.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (20, N'Think Before He Cheats', N'Digital', N'Carrie Underwood', N'Country', 2009, CAST(12.99 AS Decimal(18, 2)))
INSERT INTO [dbo].[Music] ([id], [title], [purchase_type], [performer], [genre], [year], [price]) VALUES (21, N'Cry Pretty', N'Vinyl', N'Carrie Underwood', N'Country', 2018, CAST(18.99 AS Decimal(18, 2)))
SET IDENTITY_INSERT [dbo].[Music] OFF